version: '3.7'

services:
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: Infoai517
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: Infoai517
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  webserver:
    image: apache/airflow:2.9.3
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql+mysqldb://airflow:Infoai517@mysql:3306/airflow
      AIRFLOW__CORE__FERNET_KEY: 'CsgkfxEolpHk-yAPQen50-k_ouRDI042xedttnM1BsE='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__RBAC: 'true'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: 'Asia/Shanghai'
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /data/home/graycen/project:/opt/infoai
    command: ["bash", "-c", "airflow db init && airflow users create -r Admin -u admin -p admin -e admin@example.com -f Admin -l User && airflow webserver"]

  scheduler:
    image: apache/airflow:2.9.3
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql+mysqldb://airflow:Infoai517@mysql:3306/airflow
      AIRFLOW__CORE__FERNET_KEY: 'CsgkfxEolpHk-yAPQen50-k_ouRDI042xedttnM1BsE='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__RBAC: 'true'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: 'Asia/Shanghai'
    depends_on:
      - mysql
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /data/home/graycen/project:/opt/infoai
    command: ["bash", "-c", "airflow scheduler"]

volumes:
  mysql_data:

